### PR TITLE
V1.0.2 bittorrent

### PR DESCRIPTION
**Pull request by jjoyce-bittorrent**
@richard-bt

### CODE REVIEW

**Comment by richard-bt** [comment]
I'd think this is a PR that'd make sense to submit upstream too, so that we don't have to maintain a fork.

**Comment by jjoyce-bittorrent** [comment]
https://github.com/electron-userland/electron-prebuilt/pull/165

**Comment by B-C** [comment]
electron-download already default to process.env.NPM_CONFIG_ELECTRON_MIRROR

**Comment by richard-bt** [comment]
@B-C - That doesn't appear to work because of the casing of the environment variable on Mac. On mac it's looking for all lowercase.

**Comment by B-C** [comment]
ok

**Comment by richard-bt** [comment]
For clarity, this PR is covered by the changes in Next here:
https://github.com/bt-client/next/pull/128/files

And by what's on the top of the specified branch from that PR in our electron-prebuilt:
https://github.com/bt-client/electron-prebuilt/commits/v1.0.2-bittorrent

Specifically: https://github.com/bt-client/electron-prebuilt/commit/a6d170e1fb66320b448274063b7d714aff8c6429

**Pull request closed without merging**
